echo @off
ssh root@192.168.125.1
echo Connecting to wallaby...
cd ..
cd /home\ Default User\ New Base/bin/
echo Connected to Wallaby, navigated to project folder...
exec botball_user_program
echo Running program...